%change these directories to match the folder in your computer's path
%location of the github respository:
%baseDir='D:\Min\Dropbox (Personal)\Research\Projects\FTD\mBIN\Matlab'
baseDir='/Users/min/Dropbox (Personal)/Research/Projects/FTD/mBIN/Matlab'

%Location of the data folder I send you
%Best to not put it inside a repository folder so it doesn't get accidentally committed
dataDir='/Users/min/Dropbox (Personal)/Research/Projects/FTD/Data'

%This is where all the figures will get written to. 
%Best to not put it inside a repository folder so it doesn't get accidentally committed
outputDir='/Users/min/Dropbox (Personal)/Research/Projects/FTD/tempOutput_031423'
mkdir(outputDir)

%tells matlab where to find stuff
%Shouldn't need to change
addpath(genpath(fullfile(baseDir)))

%loads the preconstructed atlas data
%Shouldn't need to change
load(fullfile(baseDir,'NetworkAnalysisGeneral','FTDGeneralData_20221114.mat'))

%Start by trying to run these script (they're located in the "LBD" folder)
%load the data
LoadDataPhasing

%Each script generates the figures in the folder:
%'.\mBIN\Matlab\PhasingAnlaysis\Code\PaperExperiments\PaperFigures'
%Scripts for the same figure needed to be ran sequentially
Fig1_PlotPhasesPoints

Fig2_GlobalMeasures

Fig3a_PlotHubsOnBrainAsPoints
Fig3bcd_AnalysisHubPerPhase

%Figure 4 is generated by running these scripts multiple times
%see comments for how to run for Fig 4a,b,c or d
Fig4ab_EpiAdjStageTrans_zscore 
Fig4cd_EdgeConnectedToHubs 

Fig5a_PrionLike
Fig5b_PrionLikeAnalysis

Fig6_matchSubToPathInfo
Fig6_relateConnectivityToPath
Fig6_visualizePath_Grouped %this last one generates the figures