inT = readtable('D:\Min\Dropbox (Personal)\Research\Projects\FTDAnalysis\Data\Working Network Path Sheet 1_29_21_wCore.xlsx');

baseSaveDir = './PaperExpCore_3_23_2021/GM/';
mkdir(baseSaveDir);

tidxKeyCore = contains(inT.Properties.VariableNames,"KeyCore");
tidxCore = contains(inT.Properties.VariableNames,"Core_GM");
tidxCore = tidxCore & ~tidxKeyCore;


removeGMRegions = {'Core_GM_ATC',...
    'Core_GM_HIP',...
    'Core_GM_M1',...
    'Core_GM_mPFC',...
    'Core_GM_PC',...
    'Core_GM_pSTC',...
    'Core_GM_S1',...
    'Core_GM_V1',...
    };

removeWMRegions = {'Core_WM_ATC',...
    'Core_WM_HIP',...
    'Core_WM_M1',...
    'Core_WM_mPFC',...
    'Core_WM_PC',...
    'Core_WM_pSTC',...
    'Core_WM_S1',...
    'Core_WM_V1',...
    };


removeRegions=removeGMRegions;

[TauMtx,TDPMtx]=analyzeGraphs(inT,tidxCore,removeRegions,baseSaveDir)

%gmT_tau=inT(inT.Tau2TDP1==2 & strcmpi(inT.ClinicalCAT,'bvFTD') ,tidx);
%gmT_tdp=inT(inT.Tau2TDP1==1 & strcmpi(inT.ClinicalCAT,'bvFTD') ,tidx);


%CompareMetrics